name: Lint and Update

on:
  push:
    paths:
      - "01/**"
      - "02/**"
      - "03/**"
      - "04/**"
      - "05/**"
      - "06/**"
      - "07/**"
      - "08/**"
      - "09/**"
      - "10/**"
      - "illustrations/**"
      - "illustrations.md"
      - "postscript.md"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: AutoCorrect
        uses: huacnlee/autocorrect-action@main

      - name: Report ReviewDog
        if: failure()
        uses: huacnlee/autocorrect-action@main
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reviewdog: true

  update:
    name: Update
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        edition:
          - web
          - epub
          - pdf
    steps:
      - name: repository_dispatch
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/proskynova/${{ matrix.edition }}/dispatches \
            -d '{"event_type":"push","client_payload":{"commit_message":"${{ github.event.head_commit.message }}"}}'
