name: Update

on:
  push:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    strategy:
      matrix:
        edition:
          - web
          - epub
          - pdf

    steps:
      - name: Update
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/proskynova/${{ matrix.edition }}/dispatches \
            -d '{"event_type":"update","client_payload":{"commit_message":"${{ github.event.head_commit.message }}"}}'
